export interface ProjectDetail {
  heading: string;
  body: string;
}

export interface Project {
  id: string;
  title: string;
  description: string;
  roles: string[];
  categories: string[];
  mediaType: "image" | "vimeo" | "foam3d";
  mediaContent: string | string[];
  link?: string;
  details?: ProjectDetail[];
  defaultHidden?: boolean;
}

export const PROJECTS: Record<string, Project> = {
  intuitive: {
    id: "intuitive",
    title: "Intuitive Surgical",
    description: "Designing and engineering advanced prototypes for future surgical video and analytics tools. Sole design engineer embedded in an advanced product design team, building case-explorer concepts that link procedure video with system data and event timelines, and prototyped interfaces for structured procedure insight and automated post-case review.",
    roles: ["Design Technologist", "Data Visualization", "AI/ML"],
    categories: ["AI", "Interactive"],
    mediaType: "image",
    mediaContent: "/images/intuitive.png",
    details: [
      {
        heading: "Context",
        body: "As Design Technologist at Intuitive Surgical, I led the Advanced Product Design group in the development of new design principles through the development of functional, production ready prototypes (internal tools and product facing) to define the direction of the Product Design team 2-3 years into the future. Prototype production focused on the following areas:",
      },
      {
        heading: "3D surgical tool path visualization",
        body: "Real-time 3D rendering of robotic instrument paths in Three.js. For the first time you could actually see how a surgeon's technique plays out spatially: where instruments went, how much force was applied, how movement tracks against procedure phase.",
      },
      {
        heading: "AI case summarization",
        body: "A local LLM system that turns structured surgical data into plain-language case summaries. ML segmentation breaks each procedure into phases, tasks, and steps. Surgeons can read what happened instead of parsing raw data.",
      },
      {
        heading: "Adaptive case explorer",
        body: "A year-long prototype that watches for unusual patterns in a procedure and pulls up the relevant data on its own, alongside historical comparisons, without anyone asking for it. Adapts to individual usage patterns over time. The core bet that held up through the whole project: users don't want all the data, they want the parts that matter.",
      },
      {
        heading: "Outcomes",
        body: "Ran a human factors study with a surgeon panel. Core assumptions confirmed. Presented to upper management; received well. Product requirements were defined from research that was still being published during the build.",
      },
    ],
  },
  agentic3d: {
    id: "agentic3d",
    title: "Agentic 3D Environments",
    description: "Ongoing UX research into agentic systems where AI agents are natively equipped with 3D visualization capabilities to communicate more effectively. Working prototype of an agent that traverses and displays user queries in a mapped 3D environment.",
    roles: ["UX Research", "AI/ML", "3D Visualization"],
    categories: ["AI", "3D", "Interactive"],
    mediaType: "image",
    mediaContent: "/images/omnitope.png",
    link: "https://omnitope-viewer-o4wbtktqi-erik-parrs-projects.vercel.app",
  },
  designsystem: {
    id: "designsystem",
    title: "Design System Case Study: Extrasensory Studio",
    description: "Built a full bidirectional pipeline between a production Next.js codebase and Figma using Tokens Studio, Figma MCP, and Claude Code as the orchestration layer. Extracted 32 primitive colors, 22 semantic tokens per theme, 13 spacing values, 8 border radius values, and 11 font sizes. Completed in a single day.",
    roles: ["Design Engineer"],
    categories: ["AI", "Interactive"],
    mediaType: "image",
    mediaContent: "/images/design-system-hero.png",
  },
  foam: {
    id: "foam",
    title: "FOAM",
    description: "AI-powered creative product that makes synthesized speech playable. Transforms voice into phonetic elements — stutters, glitch consonants, vowel textures — via MIDI or step sequencer. Built an async processing pipeline using text-to-speech APIs, forced alignment for frame-accurate phoneme boundaries, and delivers playable sample bundles orchestrated through job queues with webhook-based payments and automated error recovery. Concept to product launch in 3 weeks. Shipped and used by producers worldwide.",
    roles: ["Design", "Development", "Product"],
    categories: ["AI", "Interactive"],
    mediaType: "foam3d",
    mediaContent: "",
    link: "https://www.extrasensory.studio/foam",
  },
  extrasensory: {
    id: "extrasensory",
    title: "Extrasensory — Digital Product Studio",
    description: "Founded a digital product studio focused on creating professional tools for creative expression. First product: VEX MIDI Expression, a cross-platform audio plugin that transforms MIDI controllers into expressive instruments using real-time physics simulation. Hybrid JUCE C++ / React/TypeScript architecture achieving sub-10ms latency with sample-accurate MIDI timing. Automated CI/CD for cross-platform distribution (macOS/Windows/Linux, VST3/AU). E-commerce with Stripe integration and automated delivery.",
    roles: ["Founder", "Product Design", "Full-Stack Development", "Brand Strategy"],
    categories: ["Interactive", "AI"],
    mediaType: "image",
    mediaContent: "/images/vex.png",
    link: "https://www.extrasensory.studio",
  },
  shaders: {
    id: "shaders",
    title: "AudioVisual Web3D Shader Experiments",
    description: "Spectral audio data visualized with advanced WebGL shaders and audio-reactive 3D deformations in 3D space. R&D project for Indigo Slate.",
    roles: ["Three.js", "WebGL", "Shaders", "Audio"],
    categories: ["3D", "Interactive"],
    mediaType: "image",
    mediaContent: ["/images/shader001.gif"],
    defaultHidden: true,
  },
  adidas: {
    id: "adidas",
    title: "Adidas AR Exhibition",
    description: "Creative technical lead for the permanent Adidas AR exhibition at Adidas HQ in Germany. The experience featured interactive AR experiences triggered by physical markers throughout the space.",
    roles: ["Lead Developer", "Exhibition Design", "AR/VR"],
    categories: ["AR/VR", "Interactive", "Exhibition/Museum", "3D"],
    mediaType: "vimeo",
    mediaContent: "https://player.vimeo.com/video/345657151",
  },
  landscape: {
    id: "landscape",
    title: "Exquisite Landscape",
    description: "Generative AI art piece creating a continuously panning 24-hour landscape panorama synchronized to real time. A Railway background worker runs daily, using LangChain + OpenAI to generate 24 chained narrative prompts — each referencing the previous for continuity — then iteratively builds a seamless panorama using Stability AI's mask-based inpainting. Multi-day continuity achieved by using each day's final segment as the next day's starting point.",
    roles: ["Software Development", "AI/ML"],
    categories: ["AI", "Artwork"],
    mediaType: "image",
    mediaContent: "/images/exquisite-landscape.png",
    link: "https://landscapeclock.vercel.app",
  },
  prague: {
    id: "prague",
    title: "Prague National Gallery",
    description: "Immersive environment for projection mapping and custom generative software for visual artist Egill Saebjornsson at the Prague National Gallery.",
    roles: ["Lead Developer", "Creative Technologist", "Unity3D"],
    categories: ["Interactive", "Exhibition/Museum", "Artwork"],
    mediaType: "image",
    mediaContent: "/images/prague.png",
    defaultHidden: true,
  },
  microsoft: {
    id: "microsoft",
    title: "Microsoft Cybercrime Center",
    description: "Permanent installation at The Office for Creative Research mapping and visualizing botnets in the wild. Using realtime datasets from millions of infected computers, created an interactive application allowing data to be explored visually and sonically, giving researchers a more intuitive way of understanding botnet activity over time.",
    roles: ["Software Development", "Creative Technology", "Interactive Data Art"],
    categories: ["Interactive", "Exhibition/Museum"],
    mediaType: "image",
    mediaContent: "/images/ocr.gif",
  },
  screamometer: {
    id: "screamometer",
    title: "ScreamOmeter",
    description: "Installation at the Norwegian Science Museum where visitors break a wine glass using only their voice. A custom system incorporating architecture, software, and physical computing demonstrated the physics of sympathetic resonance as a game experience. Collaboration with Gagarin.",
    roles: ["Technical Direction", "Conceptual Development", "Creative Technology"],
    categories: ["Interactive", "Exhibition/Museum", "Mechatronic"],
    mediaType: "image",
    mediaContent: "/images/screamometer.png",
  },
  resonators: {
    id: "resonators",
    title: "Study for Resonators",
    description: "Fifty resonating structures create an evolving polyrhythmic installation transforming gallery space into a living sound sculpture. Custom software and physical computing activate the custom-designed percussive instruments, creating a perpetually evolving musical composition. Commissioned by media art festival Raflost in Reykjavik, Iceland.",
    roles: ["Art Direction", "Software Development", "Circuit Design", "Creative Technology"],
    categories: ["Interactive", "Exhibition/Museum", "Mechatronic"],
    mediaType: "image",
    mediaContent: "/images/resonators.png",
  },
  wonwei: {
    id: "wonwei",
    title: "Wonwei — Olafur Arnalds Tour",
    description: "Real-time immersive 3D visual show for musician Olafur Arnalds' world tour. Software landscapes responding to live music and performer movement via Kinect camera. Art Director and Technical Lead at Wonwei, a research-driven design and technology studio.",
    roles: ["Art Direction", "Technical Direction", "Software Dev", "Creative Technology"],
    categories: ["Interactive", "Mechatronic", "Exhibition/Museum"],
    mediaType: "image",
    mediaContent: "/images/oli.png",
  },
  iot: {
    id: "iot",
    title: "IOT Remote Irrigation System",
    description: "Using an IOT remote sensing and robotic control system, this prototype created a remote irrigation system in Portugal. The system could be monitored, controlled, and updated in realtime via an interactive web page.",
    roles: ["Technical Direction", "IOT Software Design", "Circuit Design"],
    categories: ["Interactive", "Mechatronic"],
    mediaType: "image",
    mediaContent: "/images/iot.png",
  },
  microperception: {
    id: "microperception",
    title: "Microperception Window Installation",
    description: "Visual compositions for an exhibition at Third Space Gallery in Helsinki, Finland. The works explore light phenomena and forms barely perceptible from a distance but clear on closer inspection. Custom software creates microscopic etching patterns on glass surfaces, creating a perceptual play of light, color, and reflections.",
    roles: ["Digital Laser Fabrication", "Rapid Prototyping", "Software Development", "Art Director"],
    categories: ["Exhibition/Museum", "Artwork"],
    mediaType: "image",
    mediaContent: "/images/spectralMass.png",
  },
  nanolandscapes: {
    id: "nanolandscapes",
    title: "Invisible Landscapes",
    description: "An artwork exploring the potential of nano technology as an artistic medium. Focusing on the optical possibilities of light with nano structures, combining camera obscura techniques to project nano-scale forms into architectural space. A translation across scales, as the invisible is rendered visible yet always out of reach.",
    roles: ["Creative Technologist", "Rapid Prototyping", "Software Development", "Art Director"],
    categories: ["Interactive", "Exhibition/Museum", "Artwork"],
    mediaType: "image",
    mediaContent: "/images/nano.png",
  },
  hundredthousand: {
    id: "hundredthousand",
    title: "One Hundred Thousand Landscapes",
    description: "Multi-channel sound installation creating a perpetually evolving sonic landscape from an online database of over 100,000 sound samples. The system searches for sounds matching certain descriptions, with each new sound influencing the next using spectral descriptors to search for similar sound files.",
    roles: ["Software Development", "Art Direction", "Creative Technologist"],
    categories: ["Interactive", "Exhibition/Museum", "Artwork"],
    mediaType: "image",
    mediaContent: "/images/100000Landscapes.png",
  },
  egillcommission: {
    id: "egillcommission",
    title: "Technical Production & Fabrication Commission",
    description: "Commissioned by gallery artist Egill Saebjornsson to design, develop, and build a series of artworks. The installations create a generative environment of interacting projection mapped animations and mechatronic sound sculptures. Exhibited internationally and at international art fairs.",
    roles: ["Software Development", "Hardware Development", "Physical Computing"],
    categories: ["Interactive", "Exhibition/Museum", "Artwork"],
    mediaType: "image",
    mediaContent: "/images/clinamen.png",
  },
  mechatronicsculpture: {
    id: "mechatronicsculpture",
    title: "Interactive Mechatronic Sound Sculpture",
    description: "As technical director, responsible for overall technical direction. 3D projection mapped animations trigger physical instruments powered by custom circuitry using Arduino. Developed in collaboration with the artist.",
    roles: ["Technical Director", "Software Development", "Hardware Development", "Circuit Design"],
    categories: ["Mechatronic", "Exhibition/Museum", "Artwork"],
    mediaType: "image",
    mediaContent: "/images/egill.png",
  },
  vectorprints: {
    id: "vectorprints",
    title: "Research in Computational Print Techniques",
    description: "R&D into custom software systems for generating robust vector and print graphics in C++ / openFrameworks. Developed methods for integrating cinema and photography into a generative print graphics workflow, resulting in scalable vector graphics for print or animation film.",
    roles: ["Software Development", "Artistic Research", "Creative Technology"],
    categories: ["Interactive", "Exhibition/Museum", "Artwork"],
    mediaType: "image",
    mediaContent: "/images/vectorPrints.png",
  },
  arheadtracking: {
    id: "arheadtracking",
    title: "AR Headtracking with AirPods",
    description: "Prototype showing the potential of dynamic head tracking and AR interaction with remote content using AirPods. Opens up spatial interactions including wayfinding with spatial audio cues. AirPods send motion data to the iPhone app which relays it to a server, allowing multiple screen-based apps to leverage the motion data.",
    roles: ["Lead Developer", "AR/VR", "Prototyping"],
    categories: ["AR/VR", "Interactive"],
    mediaType: "image",
    mediaContent: "https://eaca4835oc4rgi75.public.blob.vercel-storage.com/headtracking.gif",
  },
  immersivemotion: {
    id: "immersivemotion",
    title: "Immersive Motion Drawer",
    description: "Prototype using immersive 3D particles to transform body motion into an interactive experience. Built with Unity3D and a web app that uses rotation data from a mobile device to remotely interact with the 3D display, connected via Firebase realtime database.",
    roles: ["Lead Developer", "Creative Technologist", "Unity3D"],
    categories: ["AR/VR", "3D", "Interactive"],
    mediaType: "image",
    mediaContent: "https://eaca4835oc4rgi75.public.blob.vercel-storage.com/immersive-motion.gif",
  },
  interactive3dweb: {
    id: "interactive3dweb",
    title: "Interactive 3D Web Campaign",
    description: "Lead software development for a seamless 3D web experience built with Three.js and WebGL, creating a fully interactive 3D environment explorable in the browser.",
    roles: ["Lead Developer", "Three.js", "WebGL"],
    categories: ["Interactive", "3D"],
    mediaType: "image",
    mediaContent: "https://eaca4835oc4rgi75.public.blob.vercel-storage.com/suckerpunchv.gif",
  },
  touchless: {
    id: "touchless",
    title: "Touchless Web Prototypes",
    description: "Series of prototypes created in response to the covid public health crisis, envisioning ways touchless technology can be used in physical environments. Creative technology lead on the remote manipulation prototype where viewers interact with exhibit artifacts from their smartphone.",
    roles: ["Lead Developer", "AR/VR", "Three.js"],
    categories: ["AR/VR", "Interactive", "3D"],
    mediaType: "image",
    mediaContent: "https://eaca4835oc4rgi75.public.blob.vercel-storage.com/touchless-qr.gif",
  },
  futurestudio: {
    id: "futurestudio",
    title: "Future Studio Prototypes",
    description: "Prototypes for the creative research oriented Future Studio at Valtech. Built an emotion detection prototype exploring the aesthetic and technological potential of realtime facial recognition, capturing facial movements onto a 3D avatar and inferring emotional states using Apple ARKit.",
    roles: ["Lead Developer", "Creative Technologist", "AR/VR"],
    categories: ["AR/VR", "Interactive", "3D"],
    mediaType: "image",
    mediaContent: "https://eaca4835oc4rgi75.public.blob.vercel-storage.com/emotion-x.gif",
    defaultHidden: true,
  },
  webxr: {
    id: "webxr",
    title: "WebXR Experiments",
    description: "Experiments with fully web-based XR using Three.js.",
    roles: ["Lead Developer", "AR/VR", "Three.js"],
    categories: ["AR/VR", "3D"],
    mediaType: "image",
    mediaContent: "https://eaca4835oc4rgi75.public.blob.vercel-storage.com/waterCube.gif",
    defaultHidden: true,
  },
  controlnet: {
    id: "controlnet",
    title: "ControlNet Image Relighting Studio",
    description: "On-device iOS ML application using Stable Diffusion with ControlNet and Apple's Core ML framework for real-time image relighting.",
    roles: ["Software Development", "AI/ML", "iOS"],
    categories: ["AI", "Interactive"],
    mediaType: "image",
    mediaContent: "/images/controlnet-relight.png",
  },
};
